name: Deploy frontend to S3

on:
  push:
    branches: [ main ]
    paths: [ "frontend/**" ]     # フロントの変更のみトリガ

env:
  AWS_REGION: ap-northeast-1
  DIST_DIR: frontend/dist        # Next.js なら frontend/out
  S3_BUCKET: thankq-frontend-site

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------- 0. Checkout ------------------------------------------------
      - uses: actions/checkout@v4

      # ------------- 1. ビルド --------------------------------------------------
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: |
          cd frontend
          npm ci
          npm run build

      # ------------- 2. AWS 認証 (OIDC AssumeRole) -----------------------------
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_FRONTEND_ROLE_ARN }}   # 例: arn:aws:iam::1234:role/ci-frontend-deployer
          aws-region:        ${{ env.AWS_REGION }}

      # ------------- 3. 変数を一回だけ組み立てて共有 ----------------------------
      - name: Resolve resource IDs
        id: resolve
        run: |
          # CloudFront ID を Terraform Output から取得する例
          CF_ID=$(aws cloudformation describe-stacks \
                    --stack-name thankq-infra \
                    --query "Stacks[0].Outputs[?OutputKey=='cf_id'].OutputValue" \
                    --output text)
          echo "CLOUDFRONT_ID=$CF_ID" >> "$GITHUB_ENV"
          echo "SYNC_PATH=s3://${S3_BUCKET}" >> "$GITHUB_ENV"

      # ------------- 4. S3 へアップロード ---------------------------------------
      - name: Upload frontend to S3
        run: |
          aws s3 sync $DIST_DIR/ $SYNC_PATH \
            --delete \
            --cache-control "public,max-age=31536000,immutable"

      # ------------- 5. CloudFront 無効化（任意） -------------------------------
      - name: Invalidate CloudFront cache
        if: env.CLOUDFRONT_ID != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"

      # ------------- 6. CDKTF デプロイ（インフラ更新が必要なら） ---------------
      - uses: hashicorp/setup-terraform@v3
      - name: CDKTF deploy (non-interactive)
        env:
          CDKTF_DISABLE_PROMPTS: "true"
        run: |
          cd cdktf
          npm ci
          npx cdktf deploy -auto-approve
